name: Build

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2025-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Grant execute permission
      run: chmod +x gradlew
    - name: Check formatting
      run: ./gradlew lint
      env:
        CI: 'true'
    - name: Build and test
      run: ./gradlew build